ex03:
    resource: "@ex03/Controller/"
    type:     annotation
    prefix:   /

ex02:
    resource: "@ex02/Controller/"
    type:     annotation
    prefix:   /

ex01:
    resource: "@ex01/Controller/"
    type:     annotation
    prefix:   /

ex00:
    resource: "@ex00/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
