<?php

namespace ex09\Repository;

/**
 * addressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class addressesRepository extends \Doctrine\ORM\EntityRepository
{
}
