<?php

namespace ex09\Repository;

/**
 * bank_accountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bank_accountRepository extends \Doctrine\ORM\EntityRepository
{
}
