<?php

namespace ex10\Repository;

/**
 * PersonORMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonORMRepository extends \Doctrine\ORM\EntityRepository
{
}
